# Generated by Django 6.0.3 on 2026-03-11 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('floor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('room', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('free', 'Frei'), ('occupied', 'Belegt'), ('reserved', 'Reserviert'), ('maintenance', 'Außer Betrieb')], default='free', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beds', to='administrative.patient')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='administrative.station')),
            ],
            options={
                'ordering': ['station', 'room', 'bed_number'],
            },
        ),
    ]
