# Generated by Django 6.0.3 on 2026-03-12 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative', '0002_station_bed'),
        ('clinical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('occupied', 'Belegt'), ('cleaning', 'Reinigung'), ('maintenance', 'Außer Betrieb')], default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Bezeichnung des Eingriffs', max_length=255)),
                ('ops_code', models.CharField(blank=True, max_length=20)),
                ('icd_code', models.CharField(blank=True, max_length=20)),
                ('indication', models.TextField(blank=True, help_text='Indikation / Diagnose')),
                ('planned_date', models.DateField()),
                ('planned_start', models.TimeField()),
                ('planned_duration_min', models.PositiveIntegerField(default=60, help_text='Geplante Dauer in Minuten')),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Geplant'), ('in_progress', 'In Durchführung'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgesagt'), ('postponed', 'Verschoben')], default='planned', max_length=20)),
                ('priority', models.CharField(choices=[('elective', 'Elektiv'), ('urgent', 'Dringend'), ('emergency', 'Notfall')], default='elective', max_length=20)),
                ('lead_surgeon', models.CharField(max_length=100)),
                ('assistant_surgeon', models.CharField(blank=True, max_length=100)),
                ('anesthesiologist', models.CharField(blank=True, max_length=100)),
                ('scrub_nurse', models.CharField(blank=True, max_length=100)),
                ('preop_notes', models.TextField(blank=True)),
                ('postop_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='clinical.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='administrative.patient')),
                ('operation_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='operation.operationroom')),
            ],
            options={
                'ordering': ['planned_date', 'planned_start'],
            },
        ),
        migrations.CreateModel(
            name='AnesthesiaProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anesthesia_type', models.CharField(choices=[('general', 'Vollnarkose'), ('regional', 'Regionalanästhesie'), ('spinal', 'Spinalanästhesie'), ('epidural', 'Epiduralanästhesie'), ('local', 'Lokalanästhesie'), ('sedation', 'Sedierung'), ('other', 'Sonstiges')], default='general', max_length=20)),
                ('asa_classification', models.CharField(blank=True, choices=[('I', 'ASA I – Gesund'), ('II', 'ASA II – Leichte Erkrankung'), ('III', 'ASA III – Schwere Erkrankung'), ('IV', 'ASA IV – Lebensbedrohliche Erkrankung'), ('V', 'ASA V – Moribund')], max_length=5)),
                ('anesthesiologist', models.CharField(max_length=100)),
                ('induction_agent', models.CharField(blank=True, max_length=150)),
                ('maintenance_agent', models.CharField(blank=True, max_length=150)),
                ('muscle_relaxant', models.CharField(blank=True, max_length=150)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('premedication', models.TextField(blank=True)),
                ('intraop_events', models.TextField(blank=True)),
                ('recovery_notes', models.TextField(blank=True)),
                ('complications', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anesthesia', to='operation.operation')),
            ],
        ),
        migrations.CreateModel(
            name='OperationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('procedure_details', models.TextField()),
                ('findings', models.TextField(blank=True)),
                ('specimen', models.CharField(blank=True, max_length=255)),
                ('blood_loss_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('transfusions', models.CharField(blank=True, max_length=255)),
                ('complications', models.TextField(blank=True)),
                ('closing_technique', models.CharField(blank=True, max_length=255)),
                ('drains', models.CharField(blank=True, max_length=255)),
                ('postop_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='operation.operation')),
            ],
        ),
    ]
